{% set version = '1.2.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-desc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/desc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/desc/desc_{{ version }}.tar.gz
  sha256: e66fb5d4fc7974bc558abcdc107a1f258c9177a29dcfcf9164bc6b33dd08dae8

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, testthat, whoami, withr
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-r6
    - r-assertthat
    - r-crayon
    - r-rprojroot

  run:
    - r-base
    - r-r6
    - r-assertthat
    - r-crayon
    - r-rprojroot

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('desc')"           # [not win]
    - "\"%R%\" -e \"library('desc')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/r-lib/desc#readme
  license: MIT + file LICENSE
  summary: Tools to read, write, create, and manipulate DESCRIPTION files. It is intended for
    packages that create or manipulate other packages.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: desc
# Title: Manipulate DESCRIPTION Files
# Version: 1.2.0
# Authors@R: c( person("Gabor", "Csardi",, "csardi.gabor@gmail.com", role = c("aut", "cre")), person("Kirill", "Muller", role = c("aut")), person("Jim", "Hester", email = "james.f.hester@gmail.com", role = c("aut")))
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Description: Tools to read, write, create, and manipulate DESCRIPTION files. It is intended for packages that create or manipulate other packages.
# License: MIT + file LICENSE
# LazyData: true
# URL: https://github.com/r-lib/desc#readme
# BugReports: https://github.com/r-lib/desc/issues
# Depends: R (>= 3.1.0)
# Suggests: covr, testthat, whoami, withr
# Imports: assertthat, utils, R6, crayon, rprojroot
# Encoding: UTF-8
# RoxygenNote: 6.0.1.9000
# Collate: 'assertions.R' 'authors-at-r.R' 'built.R' 'classes.R' 'collate.R' 'constants.R' 'deps.R' 'description.R' 'encoding.R' 'latex.R' 'non-oo-api.R' 'package-archives.R' 'read.R' 'remotes.R' 'str.R' 'syntax_checks.R' 'urls.R' 'utils.R' 'validate.R' 'version.R'
# NeedsCompilation: no
# Packaged: 2018-05-01 20:22:08 UTC; gaborcsardi
# Author: Gabor Csardi [aut, cre], Kirill Muller [aut], Jim Hester [aut]
# Repository: CRAN
# Date/Publication: 2018-05-01 20:48:05 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
