travis:
  secure:
    BINSTAR_TOKEN: nh1waV24N4lxipm9pmANHB0apnHrcNpG7qnUePjOJ/cf0aKFFPpq8OQDtc+48k+iCWuw6ndFKTzIszFxueQlJhBUV/mBt7dE6UKEoe9bRx7/LDx4tIGBLgjUFFSQIxJBAafBrMwP9XRZOlsLHePdMY39dyEvb3A5xxCQsmLU7u6kKfivAKx/GR0Kfh1wcFaP1tOJedldW7/g8a6xq+OoKTpWL7XMqz9QWnGmbo1k/1TYqQk877k3+MgcEFr2IFYmV86RqZPDd14pfXmblTrObDWvSaqqJYrsl2UYIWBcfeeXMy684jLGpgVxI9sIW51Eae4UoLvdUax/aumhuU5CWHIVg55Ja9u6C4xRzUcYRAgnsbB93r+JOym8mnTJHwUc6M1PwUuEkI+FN1tosl8xwNRmJyilbIWhsPtOs7q99ISf/ji1g7ev+qkLpBMPIvpM7ds9XxV8Fcz/mSDuTC+e0hV0FimwT/9txGvcFkwdaASOhpRMylw/hs+gW4yB3bdIbJ1fJg2A8q+irAkNwyYFnec9/QD+jDoJIL2H326dcfmaEMzYAQ7pkO/qVLkcfu8jm3rkOYhDREu0A1RYcN0JYNBMKz9E0L4//kVGke2AsT/okQ83G2zqEiMZbDQpkkf/BRmQNr3M8vdVrxnt3cZR1QLdOp+SyZeQxSSFLZrhgCs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
