travis:
  secure:
    BINSTAR_TOKEN: IzeyD2W2S1/bsJ5qg8sF3zkHCAlHdxfUwLDVWl/LG3+tsE/GgGWKlfi6qvSBwudB5k9Iyn9krvVVj5iQhbuNIPpqDPZzWqlAl8kEh9MxqtnpiNTxyj/lwqFO4ibTdLnXdwgqPCAWJ7DnzF4HIcPRPk8xKIPkrY4qR/rzwZEkcx52oyE9zSnI2B81Ayv7FtO4WF9+cJ3ZwvaN1lo8I3JkNb+/AKz63k5HAKzNg1MdE6uiV8ZJ/4QBbLDx/gNFyWN7QJRcNKHAzjWdxU7lbtPmtx5bfLSqo+2EGgNjZ3RW/oYcTzTAPXpov91RK/UKPHfBOhcGyUVg1R2Lx49sTlAfLIc24nU/aKgNlV44k+DaEzRCUEmxdZvHi3gJNKasXx2+dv1/yfoggm8DiqQ3zeVfGaVHl9yCmRsdN1YZRQDekOh5pevnNgBmjwLgHEH+hi70hK8gkpMrW4Lh2/MxO3WnCwUNAQ4D3D06hYAPddNYVOIbSwLTebzAbqshtxZLDjuHpKeibQE2ikcnACrYKmt2YdhDEBGwXXYdJnx8DKhAuap/v9QF8eZu/VB8V9vg0CXEZLB4lARBZWfpdGbRF3DN3z1jVgcQXx68p/kNua89P/utcvPFkhDpZcQWEKkXnFwobWapyD9dCnNMZr9joQT08k/ZrVtVZ2Cd/4PgZpQ2lzs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
